# Generated by Django 4.2.3 on 2023-07-31 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auction_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
