# Generated by Django 4.2.3 on 2023-07-31 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
