# Generated by Django 4.2.3 on 2023-07-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Mezat Adı'),
        ),
    ]
