# Generated by Django 4.2.3 on 2023-08-01 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0007_alter_auction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
