# Generated by Django 4.2.3 on 2023-08-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
