# Generated by Django 4.2.3 on 2023-08-03 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_alter_auction_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_auction',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
