# Generated by Django 4.2.3 on 2023-08-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_alter_auction_start_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_auction',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
