# Generated by Django 4.2.3 on 2023-08-04 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0012_alter_auction_start_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='auction_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
